# Optimism Sepolia Deployment & Configuration

parameters:
  - &agent "0x32A0E5828B62AAb932362a4816ae03b860b65e83"

deployed:
  - &l2GovernanceExecutor "0xf695357C66bA514150Da95b189acb37b46DDe602"

l1:
  rpcUrl: https://sepolia.drpc.org # url or env var
  contracts: []

l2:
  rpcUrl: https://sepolia.optimism.io # url or env var
  contracts:
    governanceExecutor:
      name: OptimismBridgeExecutor
      address: *l2GovernanceExecutor
      checks:
        getEthereumGovernanceExecutor: *agent
        getGracePeriod: 86400
        getGuardian: "0x0000000000000000000000000000000000000000"
        getDelay: 0
        getMinimumDelay: 0
        getMaximumDelay: 1
        getActionsSetCount: 0
